apiVersion: v1
kind: Service
metadata:
  # Name of Ignite Service used by Kubernetes IP finder. 
  # The name must be equal to TcpDiscoveryKubernetesIpFinder.serviceName.
  name: gwapp-ignite
spec:
  type: LoadBalancer
  ports:
    - name: rest
      port: 8080
      targetPort: 8080
    - name: sql
      port: 10800
      targetPort: 10800
    - name: thinclients
      port: 10900
      targetPort: 10900
  # Optional - remove 'sessionAffinity' property if the Ignite cluster
  # and applications deployed within Kubernetes
  sessionAffinity: ClientIP         
  selector:
    # Must be equal to one of the labels set in Ignite pods'
    # deployement configuration.
    app: gwapp-ignite