---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ignite-console-mongodb
  labels: 
    app: ignite-console-mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ignite-console-mongodb
    spec:
      containers:
      - image: mongo:3.4
        name: ignite-console-mongodb
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-claim0
      restartPolicy: Always
      volumes:
      - name: mongodb-claim0
        persistentVolumeClaim:
          claimName: ignite-mongo-volume-claim
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ignite-mongodb
  labels:
    app: ignite-console-mongodb
spec:
  ports:
  - name: "mongodb"
    port: 27017
    targetPort: 27017
  selector:
    app: ignite-console-mongodb
status:
  loadBalancer: {}

